### ISSUE TITLE
can u please share the demo of your bot!!!

### ISSUE THREAD

**Issue by INNFINITEMINDS** [giacomocerquone/robotics-MazeSolver#1]

**Comment by giacomocerquone** [comment]
It is in my related blog post: http://blog.giacomocerquone.com/path-follower-maze-solving-car-arduino/

I forgot to add It :)

**Comment by INNFINITEMINDS** [comment]
thanks sir

**Comment by INNFINITEMINDS** [comment]
sir can u please share some resouce link of line follower robot with the help of open cv and pi
